language: java
jdk: oraclejdk8
 
script:
- cd adidas-db
- ./mvnw clean install -B
- cd ..
- cd adidas-zuul
- ./mvnw clean install -B
- cd ..
- cd adidas-eureka 
- ./mvnw clean install -B
- cd ..
- cd adidas-evt 
- ./mvnw clean install -B
- cd ..
- cd adidas-email
- ./mvnw clean install -B
- cd ..
- cd adidas-sub 
- ./mvnw clean install -B

 


