server:
  port: 2020

spring: 
  application: 
    name: adidas-zuul
    
zuul:    
  prefix: /api
  routes:
    adidas-sub:
      path: /adidas-sub/**
      service-id: adidas-sub 
      sensitive-headers: Cookie,Set-Cookie 
    adidas-evt:
      path: /adidas-evt/**
      service-id: adidas-evt 
      sensitive-headers: Cookie,Set-Cookie
    adidas-email:
      path: /adidas-email/**
      service-id: adidas-email 
      sensitive-headers: Cookie,Set-Cookie

eureka: 
   client:
     healthcheck:
      enabled: true  
     serviceUrl: 
       defaultZone: http://@url.eureka@:8080/eureka/
   instance:  
    prefer-ip-address: true
    