server:
  port: 8081

spring: 
  application: 
    name: adidas-db
  jackson:
    serialization:
      write-dates-as-timestamps: false
      
security:
  basicAuth:  
    username: spring
    password: secret 
 
eureka: 
   client:
    healthcheck:
      enabled: true 
    serviceUrl: 
      defaultZone: http://@url.eureka@:8080/eureka/
   instance:  
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
