server:
  port: 8083

spring: 
  application: 
    name: adidas-evt
  jackson:
    serialization:
      write-dates-as-timestamps: false
    
security:
  basicAuth:  
    username: spring
    password: secret 

eureka: 
   client:
     healthcheck:
      enabled: true  
     serviceUrl: 
       defaultZone: http://@url.eureka@:8080/eureka/
   instance:  
    prefer-ip-address: true